Repository 9oormthon-univ/2025_SEASONTHON_TEAM_33_BE, pull requests merged in 2025-09, with the labels that each got.

#2 [FEAT] 프로젝트 기본 세팅 #1
  .gitattributes
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/samsamejo.main.iml
  .idea/vcs.xml
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/goormthon/samsamejo/SamsamejoApplication.java
  src/main/java/com/goormthon/samsamejo/annotation/UserId.java
  src/main/java/com/goormthon/samsamejo/config/AsyncConfig.java
  src/main/java/com/goormthon/samsamejo/config/SecurityConfig.java
  src/main/java/com/goormthon/samsamejo/config/SwaggerConfig.java
  src/main/java/com/goormthon/samsamejo/constant/Constant.java
  src/main/java/com/goormthon/samsamejo/controller/TestController.java
  src/main/java/com/goormthon/samsamejo/domain/Test.java
  src/main/java/com/goormthon/samsamejo/dto/ResponseDto.java
  src/main/java/com/goormthon/samsamejo/dto/common/PageInfoDto.java
  src/main/java/com/goormthon/samsamejo/dto/request/TestCreateRequest.java
  src/main/java/com/goormthon/samsamejo/dto/response/TestCreateResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/TestReadResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/TestsReadResponse.java
  src/main/java/com/goormthon/samsamejo/exception/ErrorCode.java
  src/main/java/com/goormthon/samsamejo/exception/RestException.java
  src/main/java/com/goormthon/samsamejo/exception/handler/AsyncExceptionHandler.java
  src/main/java/com/goormthon/samsamejo/exception/handler/RestExceptionHandler.java
  src/main/java/com/goormthon/samsamejo/repository/TestRepository.java
  src/main/java/com/goormthon/samsamejo/service/TestService.java
  src/main/java/com/goormthon/samsamejo/util/FileUtil.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/goormthon/samsamejo/SamsamejoApplicationTests.java
Labels: DOCS, FEATURE, CHORE

#4 [FEAT] 인증 인가 처리 및 개인 정보 처리 페이지 구현
  .gitignore
  build.gradle
  src/main/java/com/goormthon/samsamejo/annotation/ValidFile.java
  src/main/java/com/goormthon/samsamejo/config/JpaAuditingConfig.java
  src/main/java/com/goormthon/samsamejo/config/S3Config.java
  src/main/java/com/goormthon/samsamejo/config/SecurityConfig.java
  src/main/java/com/goormthon/samsamejo/config/WebMvcConfig.java
  src/main/java/com/goormthon/samsamejo/constant/Constant.java
  src/main/java/com/goormthon/samsamejo/controller/AuthController.java
  src/main/java/com/goormthon/samsamejo/controller/TestController.java
  src/main/java/com/goormthon/samsamejo/domain/BaseEntity.java
  src/main/java/com/goormthon/samsamejo/domain/Test.java
  src/main/java/com/goormthon/samsamejo/domain/Users.java
  src/main/java/com/goormthon/samsamejo/domain/type/EProvider.java
  src/main/java/com/goormthon/samsamejo/domain/type/ERole.java
  src/main/java/com/goormthon/samsamejo/domain/type/Education.java
  src/main/java/com/goormthon/samsamejo/dto/request/TestCreateRequest.java
  src/main/java/com/goormthon/samsamejo/dto/request/auth/CareerFileRequest.java
  src/main/java/com/goormthon/samsamejo/dto/request/auth/UpdateUserInfoRequest.java
  src/main/java/com/goormthon/samsamejo/dto/request/auth/UserInfoRequest.java
  src/main/java/com/goormthon/samsamejo/dto/response/TestCreateResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/TestReadResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/TestsReadResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/security/JwtDto.java
  src/main/java/com/goormthon/samsamejo/exception/ErrorCode.java
  src/main/java/com/goormthon/samsamejo/exception/handler/AsyncExceptionHandler.java
  src/main/java/com/goormthon/samsamejo/exception/handler/RestExceptionHandler.java
  src/main/java/com/goormthon/samsamejo/interceptor/UserIdInterceptor.java
  src/main/java/com/goormthon/samsamejo/repository/TestRepository.java
  src/main/java/com/goormthon/samsamejo/repository/UsersRepository.java
  src/main/java/com/goormthon/samsamejo/resolver/UserIdArgumentResolver.java
  src/main/java/com/goormthon/samsamejo/security/exception/CustomAccessDeniedHandler.java
  src/main/java/com/goormthon/samsamejo/security/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/goormthon/samsamejo/security/factory/GoogleUserInfo.java
  src/main/java/com/goormthon/samsamejo/security/factory/KakaoUserInfo.java
  src/main/java/com/goormthon/samsamejo/security/factory/NaverUserInfo.java
  src/main/java/com/goormthon/samsamejo/security/factory/OAuth2UserInfoFactory.java
  src/main/java/com/goormthon/samsamejo/security/factory/Oauth2UserInfo.java
  src/main/java/com/goormthon/samsamejo/security/filter/ExceptionFilter.java
  src/main/java/com/goormthon/samsamejo/security/filter/JWTAuthenticationFilter.java
  src/main/java/com/goormthon/samsamejo/security/handler/login/OAuth2LoginFailureHandler.java
  src/main/java/com/goormthon/samsamejo/security/handler/login/OAuth2LoginSuccessHandler.java
  src/main/java/com/goormthon/samsamejo/security/handler/logout/CustomLogoutProcessHandler.java
  src/main/java/com/goormthon/samsamejo/security/handler/logout/CustomLogoutSuccessHandler.java
  src/main/java/com/goormthon/samsamejo/security/info/UserClaims.java
  src/main/java/com/goormthon/samsamejo/security/info/UserPrincipal.java
  src/main/java/com/goormthon/samsamejo/security/service/OAuth2UserService.java
  src/main/java/com/goormthon/samsamejo/service/AuthService.java
  src/main/java/com/goormthon/samsamejo/service/TestService.java
  src/main/java/com/goormthon/samsamejo/util/CookieUtil.java
  src/main/java/com/goormthon/samsamejo/util/HttpHeaderUtil.java
  src/main/java/com/goormthon/samsamejo/util/HttpResponseUtil.java
  src/main/java/com/goormthon/samsamejo/util/JwtUtil.java
  src/main/java/com/goormthon/samsamejo/util/S3Util.java
  src/main/java/com/goormthon/samsamejo/validator/FileValidator.java
  src/main/resources/application.yml
  src/main/resources/static/favicon.ico
Labels: FIX, FEATURE, REFACTOR, CHORE, REMOVE

#5 feat: Recruitment 모듈 기능 1~6 구현 완료
  .gitignore
  .idea/.name
  .idea/misc.xml
  .idea/vcs.xml
  src/main/java/com/goormthon/samsamejo/controller/RecruitmentController.java
  src/main/java/com/goormthon/samsamejo/controller/RecruitmentFetchLogController.java
  src/main/java/com/goormthon/samsamejo/domain/Essay.java
  src/main/java/com/goormthon/samsamejo/domain/Question.java
  src/main/java/com/goormthon/samsamejo/domain/Recruitment.java
  src/main/java/com/goormthon/samsamejo/domain/RecruitmentFetchLog.java
  src/main/java/com/goormthon/samsamejo/dto/request/EssayRequest.java
  src/main/java/com/goormthon/samsamejo/dto/request/RecruitmentEssayWriteRequest.java
  src/main/java/com/goormthon/samsamejo/dto/request/RecruitmentRequest.java
  src/main/java/com/goormthon/samsamejo/dto/response/ApiResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/PageResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/QuestionResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/RecruitmentApiResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/RecruitmentDetailResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/RecruitmentListResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/RecruitmentQuestionsResponse.java
  src/main/java/com/goormthon/samsamejo/dto/response/RecruitmentStatusResponse.java
  src/main/java/com/goormthon/samsamejo/exception/ErrorCode.java
  src/main/java/com/goormthon/samsamejo/exception/handler/RestExceptionHandler.java
  src/main/java/com/goormthon/samsamejo/repository/EssayRepository.java
  src/main/java/com/goormthon/samsamejo/repository/QuestionRepository.java
  src/main/java/com/goormthon/samsamejo/repository/RecruitmentFetchLogRepository.java
  src/main/java/com/goormthon/samsamejo/repository/RecruitmentRepository.java
  src/main/java/com/goormthon/samsamejo/service/EssayService.java
  src/main/java/com/goormthon/samsamejo/service/QuestionService.java
  src/main/java/com/goormthon/samsamejo/service/RecruitmentFetchLogService.java
  src/main/java/com/goormthon/samsamejo/service/RecruitmentService.java
  src/main/resources/application-local.yml
Labels: FEATURE

#7 [FIX] 합병 시 발생했던 충돌 문제 해결 #6
  src/main/java/com/goormthon/samsamejo/exception/ErrorCode.java
  src/main/java/com/goormthon/samsamejo/exception/handler/RestExceptionHandler.java
Labels: FIX
